version: '3.8'

services:
  web:
    build:
      context: ./meet-copilot
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    restart: unless-stopped 