import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';
import MainContent from '../components/MainContent';
import { ModalOverlay, MeetingModal } from '../components/Modal';
import '../public/assets/index-B_eBaiWL.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ zIndex: 0 }}
      >
        <div className="app-layout-vertical">
          <Header />
          <div className="main-row">
            <Sidebar />
            <MainContent>{children}</MainContent>
          </div>
          <ModalOverlay />
          <MeetingModal />
        </div>
      </body>
    </html>
  );
}
